sudo: enable
language: node_js
node_js:
  - "7"
  _ "8"
cache:
  directories:
    - "node_modules"
# # 指定分支
# branches:
#   only:
#     - test
# notifications:
#   slack: 
#     rooms:
#       - jweboytm:woLS6D9oasTaWyC1Ks4zqCne
#     on_success: change
#     on_failure: always
